config/routes.rb
Rails.application.routes.draw do
  require 'resque_web'

  resources :teams do
    get :join
  end
  resources :runs

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => "admin/resque_web"
  end

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'map#index'
  get 'about/about',  to: 'about#about'
  post 'about/send_message', to: 'about#send_message'
  get 'strava_auth',  to: 'strava_auth#strava_auth'
  get 'leader_data', to: 'leaderboard#data'
  get 'strava-webhook', to: 'strava_webhook#webhook'
  post 'strava-webhook', to: 'strava_webhook#webhook'
end

app/models/run.rb
# == Schema Information
#
# Table name: runs
#
#  id            :bigint(8)        not null, primary key
#  strava_run_id :integer
#  distance      :integer
#  date          :datetime
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Run < ApplicationRecord
  belongs_to :user

  validates :strava_run_id, uniqueness: true, allow_blank: true, allow_nil: true
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs = current_user.runs
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  # POST /runs.json
  def create
    old_run_params = run_params
    new_run_params = old_run_params.merge({user_id: current_user.id})
    @run = Run.new(new_run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { render :new }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { render :edit }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url, notice: 'Run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      #The distance units in the db will always be metres.
      if params[:run][:units] == 'miles'
        params[:run][:distance] = (params[:run][:distance].to_i * 1609).to_s
      elsif params[:run][:units] = 'kilometres'
        params[:run][:distance] = (params[:run][:distance].to_i * 1000).to_s
      end
      params.require(:run).permit(:distance, :date)
    end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.erb
<%= form_with(model: run, local: true) do |form| %>
  <% if run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :distance %>
    <%= form.number_field :distance, id: :run_distance %>
  </div>

  <div class="field" id='units_miles_or_kilometers'>
    <%= form.select :units, ['miles', 'kilometers'] %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :run_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  $(document).ready(function () {
    units = $("#units_miles_or_kilometers :selected").text();
    value = $('#run_distance').val();

    if( units == 'kilometers') {
      $('#run_distance').val(parseInt(value)/1000);
    } else if (units == 'miles'){
      $('#run_distance').val(parseInt(value)/1609);
    };

    $('#units_miles_or_kilometers').change('click', function(e){
      var selectedUnits = $(this).find(':selected').val();
      var value = $('#run_distance').val();

      if( selectedUnits == 'kilometers') {
        $('#run_distance').val(parseFloat(value)*1.60934);
      } else if (selectedUnits == 'miles'){
        $('#run_distance').val(parseFloat(value)/1.60934);
      };
    });
   });
</script>

app/views/runs/edit.html.erb
<h1>Editing Run</h1>

<%= render 'form', run: @run %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Runs</h1>

<table class='table.table-striped.table-bordered.table-hover'>
  <thead>
    <tr>
      <th class='table-header scope='col' style="width: 10%">Distance (m)</th>
      <th class='table-header scope='col' style="width: 10%">Distance (miles)</th>
      <th class='table-header scope='col' style="width: 10%">Distance (km)</th>
      <th class='table-header scope='col' style="width: 35%">Date</th>
      <th class='table-header scope='col' style="width: 5%">User</th>
      <th class='table-header scope='col' style="width: 10%">Show Link</th>
      <th class='table-header scope='col' style="width: 10%">Edit Link</th>
      <th class='table-header scope='col' style="width: 10%">Destroy Link</th>
    </tr>
  </thead>
  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= run.distance %></td>
        <td><%= run.distance/1609 unless !run.distance %></td>
        <td><%= run.distance/1000 unless !run.distance %></td>
        <td><%= run.date %></td>
        <td><%= run.user_id %></td>
        <td><%= link_to 'Show', run %></td>
        <td><%= link_to 'Edit', edit_run_path(run) %></td>
        <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Run', new_run_path, class: 'btn btn-outline-success'
 %>

<%= link_to 'Get Data From Strava', strava_authorize_request_path, class: "btn btn-outline-success #{(current_user && current_user.strava_id)  ? '':'disabled'  }"
%>
<br>

<% if !(current_user && current_user.strava_id)  %>
 <p><i>Is the update from Strava button disabled?  Please login and also set your strava id under 'edit user' :) </i></p>
<% end %>

app/views/runs/new.html.erb
<h1>New Run</h1>

<%= render 'form', run: @run %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Strava run:</strong>
  <%= @run.strava_run_id %>
</p>

<p>
  <strong>Distance (metres):</strong>
  <%= @run.distance %>
</p>

<p>
  <strong>Date:</strong>
  <%= @run.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @run.user_id %>
</p>

<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>