config/routes.rb
Rails.application.routes.draw do
  require 'resque_web'

  resources :teams do
    get :join
  end
  resources :runs

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:admin?) && current_user.admin?
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => "admin/resque_web"
  end

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'map#index'
  get 'about/about',  to: 'about#about'
  post 'about/send_message', to: 'about#send_message'
  get 'strava_auth',  to: 'strava_auth#strava_auth'
  get 'leader_data', to: 'leaderboard#data'
  get 'strava-webhook', to: 'strava_webhook#webhook'
  post 'strava-webhook', to: 'strava_webhook#webhook'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-warning">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if !user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Login',  new_user_session_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>  
        <%= link_to 'Sign Up',  new_user_registration_path, class: 'nav-link' %>
      </li>
      <% else %>
      <li class='nav-item' >
        <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'Edit User', edit_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
      <li class='nav-item'>
      <% if user_signed_in? %>
        <%= link_to 'My Runs', runs_path, class: 'nav-link'%>
      <% end %>
      </li>
      <li class='nav-item'>
      <% if user_signed_in? %>
        <%= link_to 'Teams', teams_path, class: 'nav-link'%>
      <% else %>
        <p>Teams</p>
      <% end %>
      </li>
      <li class='nav-item'>
        <%= link_to 'About/FAQ/Instructions', about_about_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
  <% if user_signed_in? %>
  <p>Hi <%= current_user.screen_name %></p>
  <% end %>
</nav>

<!-- add 'active' class to make the link active -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EastleighLejogTracker</title>
    <%= favicon_link_tag asset_path('British-Isles-Orange.gif')%>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>